version: '3.8'

services:
  api:
    container_name: ucocamp-users
    build:
      context: .
      target: ucocamp-users
    ports: 
      - 4001:4001
    volumes: 
      - .:/usr/src/app
    depends_on:
      - mongo
  
  mongo:
    container_name: ucocamp-user-database
    image: mongo
    ports:
      - 27017:27017